// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DuplicateProfile(arg1) {
  return window['go']['main']['App']['DuplicateProfile'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHotkeyConflicts() {
  return window['go']['main']['App']['GetHotkeyConflicts']();
}

export function GetHotkeyStatus() {
  return window['go']['main']['App']['GetHotkeyStatus']();
}

export function GetMediaTargets(arg1) {
  return window['go']['main']['App']['GetMediaTargets'](arg1);
}

export function GetMediaTargetsBatch(arg1) {
  return window['go']['main']['App']['GetMediaTargetsBatch'](arg1);
}

export function GetProfileStates() {
  return window['go']['main']['App']['GetProfileStates']();
}

export function GetRunningProcesses() {
  return window['go']['main']['App']['GetRunningProcesses']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function IsAutostartEnabled() {
  return window['go']['main']['App']['IsAutostartEnabled']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function MoveProfile(arg1, arg2) {
  return window['go']['main']['App']['MoveProfile'](arg1, arg2);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetGlobalHotkeysEnabled(arg1) {
  return window['go']['main']['App']['SetGlobalHotkeysEnabled'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetProfileMute(arg1, arg2) {
  return window['go']['main']['App']['SetProfileMute'](arg1, arg2);
}

export function SetProfileVolume(arg1, arg2) {
  return window['go']['main']['App']['SetProfileVolume'](arg1, arg2);
}

export function SetStartMinimized(arg1) {
  return window['go']['main']['App']['SetStartMinimized'](arg1);
}

export function TestAction(arg1, arg2) {
  return window['go']['main']['App']['TestAction'](arg1, arg2);
}
