// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {hotkey} from '../models';
import {main} from '../models';
import {process} from '../models';

export function DeleteProfile(arg1:string):Promise<config.AppConfig>;

export function DuplicateProfile(arg1:string):Promise<config.AppConfig>;

export function GetConfig():Promise<config.AppConfig>;

export function GetHotkeyConflicts():Promise<Array<hotkey.Conflict>>;

export function GetHotkeyStatus():Promise<Array<hotkey.RegistrationStatus>>;

export function GetMediaTargets(arg1:string):Promise<Array<string>>;

export function GetMediaTargetsBatch(arg1:Array<string>):Promise<Record<string, Array<string>>>;

export function GetProfileStates():Promise<Array<main.ProfileState>>;

export function GetRunningProcesses():Promise<Array<process.ProcessInfo>>;

export function HideToTray():Promise<void>;

export function IsAutostartEnabled():Promise<boolean>;

export function MinimizeWindow():Promise<void>;

export function MoveProfile(arg1:string,arg2:number):Promise<config.AppConfig>;

export function SaveProfile(arg1:config.ProcessProfile):Promise<config.AppConfig>;

export function SetAutostart(arg1:boolean):Promise<config.AppConfig>;

export function SetGlobalHotkeysEnabled(arg1:boolean):Promise<config.AppConfig>;

export function SetLanguage(arg1:string):Promise<config.AppConfig>;

export function SetProfileMute(arg1:string,arg2:boolean):Promise<main.ProfileState>;

export function SetProfileVolume(arg1:string,arg2:number):Promise<main.ProfileState>;

export function SetStartMinimized(arg1:boolean):Promise<config.AppConfig>;

export function TestAction(arg1:string,arg2:config.ActionType):Promise<string>;
